"""add Category, Brand, product_category, product_brand for filters

Revision ID: 21ed66338317
Revises: d9517908c3aa
Create Date: 2026-05-09 20:12:33.225727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21ed66338317'
down_revision = 'd9517908c3aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('remote_id', sa.String(length=120), nullable=True),
    sa.Column('remote_source', sa.String(length=40), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'remote_source', 'remote_id', name='uq_brand_account_remote')
    )
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_account_id'), ['account_id'], unique=False)

    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('remote_id', sa.String(length=120), nullable=True),
    sa.Column('remote_source', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'remote_source', 'remote_id', name='uq_category_account_remote')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_category_account_parent', ['account_id', 'parent_id'], unique=False)

    op.create_table('product_brand',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'brand_id')
    )
    op.create_table('product_category',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_category')
    op.drop_table('product_brand')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index('ix_category_account_parent')
        batch_op.drop_index(batch_op.f('ix_category_account_id'))

    op.drop_table('category')
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_account_id'))

    op.drop_table('brand')
    # ### end Alembic commands ###
