"""add account_type to Account

Revision ID: 323fcac58ee0
Revises: 48e2c30181ce
Create Date: 2026-05-09 17:44:51.097009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323fcac58ee0'
down_revision = '48e2c30181ce'
branch_labels = None
depends_on = None


def upgrade():
    # server_default='store' is critical: existing Account rows (the seeded
    # admin account on Heroku) need a value to satisfy NOT NULL.
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'account_type', sa.String(length=20),
            nullable=False, server_default='store',
        ))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('account_type')

    # ### end Alembic commands ###
