"""WC field parity: promoted Product columns, Tag taxonomy, ChannelLink.raw_remote_data

Revision ID: 3f5262798910
Revises: 21ed66338317
Create Date: 2026-05-09 20:29:32.378828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f5262798910'
down_revision = '21ed66338317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('remote_id', sa.String(length=120), nullable=True),
    sa.Column('remote_source', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'remote_source', 'remote_id', name='uq_tag_account_remote')
    )
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_account_id'), ['account_id'], unique=False)

    op.create_table('product_tag',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'tag_id')
    )
    with op.batch_alter_table('channel_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_remote_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('length_mm', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('width_mm', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('height_mm', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vendor', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('short_description', sa.Text(), nullable=True))
        # server_default='false' so existing rows get a value (NOT NULL would
        # otherwise fail on Heroku where products already exist). 'false' is
        # portable across SQLite (stores as 0) and Postgres (native boolean).
        batch_op.add_column(sa.Column('featured', sa.Boolean(), nullable=False,
                                      server_default=sa.text('false')))
        batch_op.add_column(sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('sale_starts_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sale_ends_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('sale_ends_at')
        batch_op.drop_column('sale_starts_at')
        batch_op.drop_column('sale_price')
        batch_op.drop_column('featured')
        batch_op.drop_column('short_description')
        batch_op.drop_column('slug')
        batch_op.drop_column('vendor')
        batch_op.drop_column('height_mm')
        batch_op.drop_column('width_mm')
        batch_op.drop_column('length_mm')

    with op.batch_alter_table('channel_link', schema=None) as batch_op:
        batch_op.drop_column('raw_remote_data')

    op.drop_table('product_tag')
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_account_id'))

    op.drop_table('tag')
    # ### end Alembic commands ###
