"""initial schema

Revision ID: 48e2c30181ce
Revises: 
Create Date: 2026-05-09 10:06:20.542756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48e2c30181ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('api_key_enc', sa.Text(), nullable=True),
    sa.Column('api_secret_enc', sa.Text(), nullable=True),
    sa.Column('webhook_secret_enc', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channel_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_account_account_id'), ['account_id'], unique=False)

    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('compare_at_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('weight_grams', sa.Integer(), nullable=True),
    sa.Column('requires_shipping', sa.Boolean(), nullable=False),
    sa.Column('tax_class', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_pushed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'sku', name='uq_product_account_sku')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_account_id'), ['account_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('product_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('alt', sa.String(length=255), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_image_product_id'), ['product_id'], unique=False)

    op.create_table('product_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('option1_name', sa.String(length=60), nullable=True),
    sa.Column('option1_value', sa.String(length=60), nullable=True),
    sa.Column('option2_name', sa.String(length=60), nullable=True),
    sa.Column('option2_value', sa.String(length=60), nullable=True),
    sa.Column('option3_name', sa.String(length=60), nullable=True),
    sa.Column('option3_value', sa.String(length=60), nullable=True),
    sa.Column('price_override', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('inventory_quantity', sa.Integer(), nullable=False),
    sa.Column('inventory_policy', sa.String(length=20), nullable=False),
    sa.Column('barcode', sa.String(length=120), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variant_product_id'), ['product_id'], unique=False)

    op.create_table('sync_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('channel_account_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['channel_account_id'], ['channel_account.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_job_account_id'), ['account_id'], unique=False)

    op.create_table('webhook_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_account_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('process_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['channel_account_id'], ['channel_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_event_channel_account_id'), ['channel_account_id'], unique=False)

    op.create_table('channel_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('channel_account_id', sa.Integer(), nullable=False),
    sa.Column('remote_product_id', sa.String(length=120), nullable=True),
    sa.Column('remote_variant_id', sa.String(length=120), nullable=True),
    sa.Column('remote_sku', sa.String(length=120), nullable=True),
    sa.Column('last_pushed_at', sa.DateTime(), nullable=True),
    sa.Column('last_pulled_at', sa.DateTime(), nullable=True),
    sa.Column('remote_version', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['channel_account_id'], ['channel_account.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_account_id', 'remote_product_id', 'remote_variant_id', name='uq_link_remote')
    )
    with op.batch_alter_table('channel_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_link_channel_account_id'), ['channel_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_link_product_id'), ['product_id'], unique=False)

    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('channel_account_id', sa.Integer(), nullable=False),
    sa.Column('remote_order_id', sa.String(length=120), nullable=False),
    sa.Column('sku', sa.String(length=120), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('ordered_at', sa.DateTime(), nullable=False),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['channel_account_id'], ['channel_account.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_account_id', 'remote_order_id', 'sku', name='uq_order_per_line')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_channel_account_id'), ['channel_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_sku'), ['sku'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_sku'))
        batch_op.drop_index(batch_op.f('ix_order_channel_account_id'))
        batch_op.drop_index(batch_op.f('ix_order_account_id'))

    op.drop_table('order')
    with op.batch_alter_table('channel_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_link_product_id'))
        batch_op.drop_index(batch_op.f('ix_channel_link_channel_account_id'))

    op.drop_table('channel_link')
    with op.batch_alter_table('webhook_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_event_channel_account_id'))

    op.drop_table('webhook_event')
    with op.batch_alter_table('sync_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_job_account_id'))

    op.drop_table('sync_job')
    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variant_product_id'))

    op.drop_table('product_variant')
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_image_product_id'))

    op.drop_table('product_image')
    op.drop_table('user')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_account_id'))

    op.drop_table('product')
    with op.batch_alter_table('channel_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_account_account_id'))

    op.drop_table('channel_account')
    op.drop_table('account')
    # ### end Alembic commands ###
