"""add User.is_admin and backfill seeded admin

Revision ID: 566a17cad730
Revises: 323fcac58ee0
Create Date: 2026-05-09 19:06:02.171795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566a17cad730'
down_revision = '323fcac58ee0'
branch_labels = None
depends_on = None


def upgrade():
    # server_default='0' lets existing User rows get a value (NOT NULL would
    # otherwise reject them on Heroku where the seeded admin already exists).
    # '0' is portable across SQLite (no native bool) and Postgres (cast).
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'is_admin', sa.Boolean(),
            nullable=False, server_default='0',
        ))
    # Backfill: the seeded admin is the first platform admin. Quoted "user"
    # because it's a reserved word in Postgres. Use TRUE (not 1) — Postgres
    # rejects integer-to-boolean implicit casts in UPDATE; modern SQLite
    # (>=3.23, 2018) also accepts TRUE so the migration stays portable.
    op.execute("UPDATE \"user\" SET is_admin = TRUE WHERE email = 'admin@example.com'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
