"""add Account profile fields for signup divergence

Revision ID: d9517908c3aa
Revises: 566a17cad730
Create Date: 2026-05-09 19:23:49.323732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9517908c3aa'
down_revision = '566a17cad730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('industry', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('current_platforms', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('product_count_estimate', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('product_count_estimate')
        batch_op.drop_column('current_platforms')
        batch_op.drop_column('country')
        batch_op.drop_column('website')
        batch_op.drop_column('industry')

    # ### end Alembic commands ###
